
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Assignment2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Booking
{

    public int BookingID { get; set; }

    public int RoomID { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public int DaysStaying { get; set; }

    public System.DateTime BookDate { get; set; }

}

}
