

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Assignment2.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class comp2007Entities : DbContext
{
    public comp2007Entities()
        : base("name=DefaultConnectionEF")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Room> Rooms { get; set; }

    public virtual DbSet<Booking> Bookings { get; set; }

}

}

